### ISSUE TITLE
Error when trying to add

### ISSUE THREAD

**Issue by Ainali** [egils-consulting/LexUse#4]
```
Presenting sentence 1/6 from 2016-09-20 from https://data.riksdagen.se/dokument/H4031d22
Found the following sentence with 8 words. Is it suitable as a usage example for the form 'metallerna'? 
'Hit räknas även metallerna bly, kvicksilver och kadmium.' [(Y)es/(n)o/(s)kip this form]: y
Found only one sense. Does this example fit the following gloss? 
'grundämne eller legering med metalliska egenskaper' [Y/n]: y
Traceback (most recent call last):
  File "swedish.py", line 49, in <module>
    main()
  File "swedish.py", line 45, in main
    util.process_lexeme_data(results)
  File "/home/ainali/github/LexUse/util.py", line 687, in process_lexeme_data
    process_result(result, data)
  File "/home/ainali/github/LexUse/util.py", line 603, in process_result
    form_of_utterance=medium,
  File "/home/ainali/github/LexUse/util.py", line 509, in present_sentence
    form_of_utterance=form_of_utterance,
  File "/home/ainali/github/LexUse/util.py", line 205, in add_usage_example
    publication_date = datetime.fromisoformat(publication_date)
AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'
```
I run Ubuntu 18.04.5 LTS with Python 3.6.9.

**Comment by dpriskorn** [comment]
A required function seems to be missing in your very old Python version. 
See https://pypi.org/project/backports-datetime-fromisoformat/
It was added in 3.7 which is now the minimum version required. 
Please upgrade your Python version. 
It's possible to upgrade only python, but it breaks apt so you should upgrade Ubuntu. 
See https://dev.to/serhatteker/how-to-upgrade-to-python-3-7-on-ubuntu-18-04-18-10-5hab
